name: Version Release Check

on:
  release:
    types: [published]
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string
      rust_version:
        required: true
        type: string

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  CARGO_INCREMENTAL: 0
  MOZJS_REPO: ${{ github.repository }}
  RUST_TOOLCHAIN_INPUT: ${{ github.event_name == 'release' && '1.85.0' ||  inputs.rust_version }}

jobs:
  verify-archive:
    strategy:
      fail-fast: false
      matrix:
        features: ["debugmozjs", ""]
        platform:
          - { target: aarch64-apple-darwin, os: macos-14 }
          - { target: x86_64-apple-darwin, os: macos-15-intel }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: aarch64-pc-windows-msvc, os: windows-11-arm }
    runs-on: ${{ matrix.platform.os }}
    env:
      RELEASE_TAG: ${{ github.event_name == 'release' && github.ref_name || inputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_INPUT }}
          targets: ${{ matrix.platform.target }}
      - name: Download prebuilt mozjs from artifact
        if: ${{ env.RELEASE_TAG == '' }}
        uses: actions/download-artifact@v4
        with:
          name: libmozjs-${{ matrix.platform.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
      - name: Build from archive
        if: ${{ env.RELEASE_TAG == '' }}
        env:
          MOZJS_ARCHIVE: libmozjs-${{ matrix.platform.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
        run: |
          cargo +${{ steps.toolchain.outputs.name }} build --verbose  --features "${{ matrix.features }}"
          cargo +${{ steps.toolchain.outputs.name }} test --tests --examples --verbose  --features "${{ matrix.features }}"
      - name: Build from auto-download
        if: ${{ env.RELEASE_TAG != '' }}
        env:
          MOZJS_ATTESTATION: strict
        run: |
          cargo +${{ steps.toolchain.outputs.name }} build --verbose  --features "${{ matrix.features }}"
          cargo +${{ steps.toolchain.outputs.name }} test --tests --examples --verbose  --features "${{ matrix.features }}"

  verify-archive-android:
    name: "Verify archive Android"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["debugmozjs", ""]
        target:
          [
            "armv7-linux-androideabi",
            "aarch64-linux-android",
            "x86_64-linux-android",
          ]
    env:
      RELEASE_TAG: ${{ github.event_name == 'release' && github.ref_name ||  inputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Install NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_INPUT }}
          targets: ${{ matrix.target }}
      - name: Download prebuilt mozjs from artifact
        if: ${{ env.RELEASE_TAG == '' }}
        uses: actions/download-artifact@v4
        with:
          name: libmozjs-${{ matrix.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
      - name: Build from archive
        if: ${{ env.RELEASE_TAG == '' }}
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
          MOZJS_ARCHIVE: libmozjs-${{ matrix.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
        run: |
          ./android-build cargo +${{ steps.toolchain.outputs.name }} build --target="${{ matrix.target }}" --features "${{ matrix.features }}" --verbose
      - name: Build from auto-download (arch ${{ matrix.target }})
        if: ${{ env.RELEASE_TAG != '' }}
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
          MOZJS_ATTESTATION: strict
        run: |
          ./android-build cargo +${{ steps.toolchain.outputs.name }} build --target="${{ matrix.target }}" --features "${{ matrix.features }}" --verbose

  verify-archive-ohos:
    name: "Verify archive OpenHarmony"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["debugmozjs", ""]
        target: ["aarch64-unknown-linux-ohos", "x86_64-unknown-linux-ohos"]
    env:
      RELEASE_TAG: ${{ github.event_name == 'release' && github.ref_name ||  inputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup OpenHarmony SDK
        id: setup_sdk
        uses: openharmony-rs/setup-ohos-sdk@v0.1
        with:
          version: "4.1"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_INPUT }}
          targets: ${{ matrix.target }}
      - name: Download prebuilt mozjs from artifact
        if: ${{ env.RELEASE_TAG == '' }}
        uses: actions/download-artifact@v4
        with:
          name: libmozjs-${{ matrix.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
      - name: Build from archive
        if: ${{ env.RELEASE_TAG == '' }}
        env:
          OHOS_SDK_NATIVE: ${{ steps.setup_sdk.outputs.ohos_sdk_native }}
          MOZJS_ARCHIVE: libmozjs-${{ matrix.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
        run: |
          ./ohos-build cargo +${{ steps.toolchain.outputs.name }} build --target="${{ matrix.target }}" --features "${{ matrix.features }}" --verbose
      - name: Build from auto-download (arch ${{ matrix.target }})
        if: ${{ env.RELEASE_TAG != '' }}
        env:
          OHOS_SDK_NATIVE: ${{ steps.setup_sdk.outputs.ohos_sdk_native }}
          MOZJS_ATTESTATION: strict
        run: |
          ./ohos-build cargo +${{ steps.toolchain.outputs.name }} build --target="${{ matrix.target }}" --features "${{ matrix.features }}" --verbose

  verify-archive-linux-cross:
    name: "Verify archive linux (${{ matrix.target }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: ["debugmozjs", ""]
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
    container: ghcr.io/servo/cross-${{ matrix.target }}:main
    env:
      RELEASE_TAG: ${{ github.event_name == 'release' && github.ref_name || inputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_INPUT }}
          targets: ${{ matrix.target }}
      - name: Download prebuilt mozjs from artifact
        if: ${{ env.RELEASE_TAG == '' }}
        uses: actions/download-artifact@v4
        with:
          name: libmozjs-${{ matrix.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
      - name: Build from archive
        if: ${{ env.RELEASE_TAG == '' }}
        env:
          MOZJS_ARCHIVE: libmozjs-${{ matrix.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
        run: |
          cargo +${{ steps.toolchain.outputs.name }} build --verbose --target ${{ matrix.target }} --features "${{ matrix.features }}"
      - name: Build from auto-download
        if: ${{ env.RELEASE_TAG != '' }}
        env:
          MOZJS_ATTESTATION: strict
        run: |
          cargo +${{ steps.toolchain.outputs.name }} build --verbose --target ${{ matrix.target }} --features "${{ matrix.features }}"

  verify-archive-wasi:
    name: "Verify archive WASI"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: ["debugmozjs", ""]
        target:
          - wasip1
          - wasip2
    env:
      RELEASE_TAG: ${{ github.event_name == 'release' && github.ref_name ||  inputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_INPUT }}
          targets: "wasm32-${{ matrix.target }}"
      - name: Install WASI-SDK
        run: |
          cd /tmp
          curl --retry 5 --retry-all-errors -OL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-linux.tar.gz
          tar -xzf wasi-sdk-25.0-x86_64-linux.tar.gz
          mv wasi-sdk-25.0-x86_64-linux wasi-sdk
      - name: Download prebuilt mozjs from artifact
        if: ${{ env.RELEASE_TAG == '' }}
        uses: actions/download-artifact@v4
        with:
          name: libmozjs-wasm32-${{ matrix.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
      - name: Build from archive
        if: ${{ env.RELEASE_TAG == '' }}
        env:
          WASI_SDK_PATH: "/tmp/wasi-sdk"
          MOZJS_ARCHIVE: libmozjs-wasm32-${{ matrix.target }}${{ matrix.features && '-debugmozjs' || '' }}.tar.gz
        run: |
          cargo +${{ steps.toolchain.outputs.name }} build --target=wasm32-${{ matrix.target }} --features "${{ matrix.features }}" --verbose
      - name: Build from auto-download
        if: ${{ env.RELEASE_TAG != '' }}
        env:
          WASI_SDK_PATH: "/tmp/wasi-sdk"
          MOZJS_ATTESTATION: strict
        run: |
          cargo +${{ steps.toolchain.outputs.name }} build --target=wasm32-${{ matrix.target }} --features "${{ matrix.features }}" --verbose
