[package]
license = "MPL-2.0"
description = "copy of properties_glue for mozjs-sys"
links = "properties_glue"
repository = "https://github.com/servo/mozjs"
name = "mozjs_properties_glue"
version = "153.0.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
icu_properties = { version = "2.1.2", default-features = false, features = ["alloc", "serde"] }
icu_collections = { features = ["alloc"], package = "mozjs_icu_collections", version = "=153.0.0", path = "../icu_collections" }
icu_casemap = { version = "2", default-features = false, features = ["serde"] }
icu_provider_glue = { package = "mozjs_icu_provider_glue", version = "=153.0.0", path = "../icu_provider_glue" }

[build-dependencies.cbindgen]
version = "0.29.4"
